<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Laboratory;

class LaboratorySeeder extends Seeder
{
    public function run(): void
    {
        Laboratory::query()->delete();

        $labs = [
            // --- JABODETABEK & BANTEN ---
            [
                'lab_id' => 'LAB-BRIN-001',
                'campus_name' => 'Kawasan Sains dan Teknologi Soekarno',
                'faculty' => 'Pusat Riset Material Maju BRIN',
                'lab_name' => 'BRIN Cibinong Advanced Characterization Lab',
                'category' => 'Material & Kimia',
                'capacity' => 25,
                'address_description' => 'Gedung 410 KST Soekarno, Cibinong, Bogor',
                'latitude' => -6.49120000,
                'longitude' => 106.84850000,
                'base_price_per_session' => 350000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UI-001',
                'campus_name' => 'Kampus UI Depok',
                'faculty' => 'Laboratorium Sentral FMIPA UI',
                'lab_name' => 'Central Lab UI (Integrated Bio-Testing)',
                'category' => 'Bioteknologi',
                'capacity' => 40,
                'address_description' => 'Gedung Lab Riset Multidisiplin FMIPA UI, Depok',
                'latitude' => -6.36440000,
                'longitude' => 106.82860000,
                'base_price_per_session' => 450000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-BRIN-002',
                'campus_name' => 'Kawasan Riset BJ Habibie Serpong',
                'faculty' => 'Pusat Riset Teknologi Nuklir BRIN',
                'lab_name' => 'Kawasan Riset BJ Habibie Serpong BRIN',
                'category' => 'Energi Terbarukan',
                'capacity' => 30,
                'address_description' => 'Gedung 720 Puspiptek Serpong, Tangerang Selatan',
                'latitude' => -6.35300000,
                'longitude' => 106.66900000,
                'base_price_per_session' => 500000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-IPB-001',
                'campus_name' => 'Kampus IPB Dramaga',
                'faculty' => 'Layanan Analisis & Pengujian Terpadu',
                'lab_name' => 'Advanced Characterization & Testing IPB',
                'category' => 'Pertanian & Pangan',
                'capacity' => 35,
                'address_description' => 'Gedung Lab Terpadu IPB Dramaga, Bogor',
                'latitude' => -6.55620000,
                'longitude' => 106.72310000,
                'base_price_per_session' => 270000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UINJKT-001',
                'campus_name' => 'Kampus 1 UIN Syarif Hidayatullah',
                'faculty' => 'Fakultas Sains dan Teknologi',
                'lab_name' => 'Laboratorium Terpadu UIN Syarif Hidayatullah',
                'category' => 'Farmasi & Medis',
                'capacity' => 30,
                'address_description' => 'Jl. Ir H. Juanda No.95, Ciputat, Tangerang Selatan',
                'latitude' => -6.30820000,
                'longitude' => 106.75700000,
                'base_price_per_session' => 230000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UP-001',
                'campus_name' => 'Kampus Utama Universitas Pancasila',
                'faculty' => 'Fakultas Farmasi',
                'lab_name' => 'Laboratorium Pengujian Biomedis Universitas Pancasila',
                'category' => 'Farmasi & Medis',
                'capacity' => 25,
                'address_description' => 'Srengseng Sawah, Jagakarsa, Jakarta Selatan',
                'latitude' => -6.33850000,
                'longitude' => 106.83220000,
                'base_price_per_session' => 310000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-BRIN-003',
                'campus_name' => 'KST Soekarno Cibinong',
                'faculty' => 'Pusat Riset Biomaterial BRIN',
                'lab_name' => 'Laboratorium Riset Biomaterial BRIN Cibinong',
                'category' => 'Material & Kimia',
                'capacity' => 20,
                'address_description' => 'Gedung Biomaterial KST Soekarno, Cibinong',
                'latitude' => -6.49150000,
                'longitude' => 106.84800000,
                'base_price_per_session' => 290000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-TRISAKTI-001',
                'campus_name' => 'Kampus A Grogol',
                'faculty' => 'Fakultas Teknologi Kebumian dan Energi',
                'lab_name' => 'Laboratorium Sentral Universitas Trisakti',
                'category' => 'Energi Terbarukan',
                'capacity' => 30,
                'address_description' => 'Jl. Kyai Tapa No.1, Grogol, Jakarta Barat',
                'latitude' => -6.16890000,
                'longitude' => 106.78920000,
                'base_price_per_session' => 330000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-ATMA-001',
                'campus_name' => 'Kampus Pluit',
                'faculty' => 'Fakultas Kedokteran dan Ilmu Kesehatan',
                'lab_name' => 'Laboratorium Biologi Molekuler Unika Atma Jaya',
                'category' => 'Bioteknologi',
                'capacity' => 20,
                'address_description' => 'Jl. Pluit Raya No.2, Penjaringan, Jakarta Utara',
                'latitude' => -6.12650000,
                'longitude' => 106.79510000,
                'base_price_per_session' => 360000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UHAMKA-001',
                'campus_name' => 'Kampus Klender',
                'faculty' => 'Fakultas Farmasi dan Sains',
                'lab_name' => 'Pusat Laboratorium Terpadu Uhamka',
                'category' => 'Farmasi & Medis',
                'capacity' => 25,
                'address_description' => 'Jl. Delima II, Klender, Duren Sawit, Jakarta Timur',
                'latitude' => -6.22550000,
                'longitude' => 106.88330000,
                'base_price_per_session' => 220000.00,
                'is_active' => true,
            ],

            // --- JAWA BARAT & BANDUNG ---
            [
                'lab_id' => 'LAB-ITB-001',
                'campus_name' => 'Kampus ITB Ganesha',
                'faculty' => 'Pusat Nanosains dan Nanoteknologi',
                'lab_name' => 'ITB Center for Nanotechnology & Advanced Materials',
                'category' => 'Nanoteknologi',
                'capacity' => 30,
                'address_description' => 'Gedung CAS ITB Lt. 3, Jl. Ganesha No.10, Bandung',
                'latitude' => -6.89150000,
                'longitude' => 107.61070000,
                'base_price_per_session' => 280000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNPAD-001',
                'campus_name' => 'Kampus Unpad Jatinangor',
                'faculty' => 'Central Laboratory Unpad',
                'lab_name' => 'Central Laboratory UNPAD Jatinangor',
                'category' => 'Farmasi & Medis',
                'capacity' => 45,
                'address_description' => 'Jl. Raya Bandung-Sumedang Km.21, Jatinangor',
                'latitude' => -6.92880000,
                'longitude' => 107.77190000,
                'base_price_per_session' => 380000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-ITB-002',
                'campus_name' => 'Kampus ITB Ganesha',
                'faculty' => 'School of Life Sciences and Technology',
                'lab_name' => 'Laboratorium Rekayasa Genetika & Proteomika ITB',
                'category' => 'Bioteknologi',
                'capacity' => 25,
                'address_description' => 'Gedung Labtek XI ITB, Jl. Ganesha No.10, Bandung',
                'latitude' => -6.89080000,
                'longitude' => 107.61010000,
                'base_price_per_session' => 420000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-TELKOM-001',
                'campus_name' => 'Telkom University Dayeuhkolot',
                'faculty' => 'Fakultas Industri Kreatif',
                'lab_name' => 'Laboratorium Pengujian Tekstil Telkom University',
                'category' => 'Material & Kimia',
                'capacity' => 30,
                'address_description' => 'Gedung FIK Telkom University, Bandung',
                'latitude' => -6.97400000,
                'longitude' => 107.63050000,
                'base_price_per_session' => 200000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-BRIN-004',
                'campus_name' => 'Kawasan Riset BRIN Bandung',
                'faculty' => 'Pusat Riset Geoteknologi BRIN',
                'lab_name' => 'Pusat Riset Geoteknologi BRIN Bandung',
                'category' => 'Lingkungan & Lingkup Laut',
                'capacity' => 20,
                'address_description' => 'Komplek LIPI Sangkuriang, Dago, Bandung',
                'latitude' => -6.88330000,
                'longitude' => 107.61250000,
                'base_price_per_session' => 310000.00,
                'is_active' => true,
            ],

            // --- DI YOGYAKARTA & JAWA TENGAH ---
            [
                'lab_id' => 'LAB-UGM-001',
                'campus_name' => 'Kampus UGM Bulaksumur',
                'faculty' => 'LPPT UGM',
                'lab_name' => 'Laboratorium Penelitian dan Pengujian Terpadu UGM',
                'category' => 'Material & Kimia',
                'capacity' => 50,
                'address_description' => 'Sekip Utara, Bulaksumur, Sleman, DI Yogyakarta',
                'latitude' => -7.77010000,
                'longitude' => 110.37780000,
                'base_price_per_session' => 300000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNDIP-001',
                'campus_name' => 'Kampus Undip Tembalang',
                'faculty' => 'Laboratorium Terpadu Undip',
                'lab_name' => 'Laboratorium Terpadu Universitas Diponegoro',
                'category' => 'Lingkungan & Lingkup Laut',
                'capacity' => 40,
                'address_description' => 'Jl. Prof. Soedarto, SH, Tembalang, Semarang',
                'latitude' => -7.05050000,
                'longitude' => 110.43710000,
                'base_price_per_session' => 290000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNS-001',
                'campus_name' => 'Kampus UNS Kentingan',
                'faculty' => 'Laboratorium Terpadu UNS',
                'lab_name' => 'Laboratorium Terpadu Sains UNS',
                'category' => 'Material & Kimia',
                'capacity' => 35,
                'address_description' => 'Jl. Ir. Sutami No.36A, Kentingan, Surakarta',
                'latitude' => -7.55830000,
                'longitude' => 110.85620000,
                'base_price_per_session' => 260000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNY-001',
                'campus_name' => 'Kampus UNY Karangmalang',
                'faculty' => 'Fakultas MIPA',
                'lab_name' => 'Laboratorium Bioteknologi Terpadu UNY',
                'category' => 'Bioteknologi',
                'capacity' => 30,
                'address_description' => 'Karangmalang, Caturtunggal, Depok, Sleman',
                'latitude' => -7.77380000,
                'longitude' => 110.38620000,
                'base_price_per_session' => 240000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UII-001',
                'campus_name' => 'Kampus Terpadu UII Kaliurang',
                'faculty' => 'Fakultas Matematika dan IPA',
                'lab_name' => 'Laboratorium Farmasi Analisis UII Yogyakarta',
                'category' => 'Farmasi & Medis',
                'capacity' => 30,
                'address_description' => 'Jl. Kaliurang Km. 14,5, Sleman, DI Yogyakarta',
                'latitude' => -7.68740000,
                'longitude' => 110.41430000,
                'base_price_per_session' => 280000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UMS-001',
                'campus_name' => 'Kampus 2 UMS Pabelan',
                'faculty' => 'Fakultas Teknik',
                'lab_name' => 'Laboratorium Terpadu UMS Surakarta',
                'category' => 'Material & Kimia',
                'capacity' => 25,
                'address_description' => 'Jl. A. Yani, Pabelan, Kartasura, Sukoharjo',
                'latitude' => -7.55770000,
                'longitude' => 110.77180000,
                'base_price_per_session' => 230000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNSOED-001',
                'campus_name' => 'Kampus Unsoed Purwokerto',
                'faculty' => 'Fakultas MIPA',
                'lab_name' => 'Laboratorium Analisis Lingkungan Unsoed',
                'category' => 'Lingkungan & Lingkup Laut',
                'capacity' => 30,
                'address_description' => 'Jl. Dr. Soeparno, Karangwangkal, Purwokerto',
                'latitude' => -7.40220000,
                'longitude' => 109.25010000,
                'base_price_per_session' => 210000.00,
                'is_active' => true,
            ],

            // --- JAWA TIMUR ---
            [
                'lab_id' => 'LAB-UNAIR-001',
                'campus_name' => 'Kampus C Mulyorejo',
                'faculty' => 'Pusat Riset Molekuler & Genomic',
                'lab_name' => 'Pusat Riset Molekuler & Genomic UNAIR',
                'category' => 'Bioteknologi',
                'capacity' => 35,
                'address_description' => 'Gedung Nanoriset UNAIR Lt. 2, Mulyorejo, Surabaya',
                'latitude' => -7.26800000,
                'longitude' => 112.78500000,
                'base_price_per_session' => 400000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-ITS-001',
                'campus_name' => 'Kampus ITS Sukolilo',
                'faculty' => 'Fakultas Teknologi Industri dan Rekayasa Sistem',
                'lab_name' => 'Laboratorium Energi & Material Maju ITS',
                'category' => 'Energi Terbarukan',
                'capacity' => 40,
                'address_description' => 'Gedung Riset ITS Sukolilo, Surabaya',
                'latitude' => -7.28220000,
                'longitude' => 112.79440000,
                'base_price_per_session' => 250000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UB-001',
                'campus_name' => 'Kampus Utama UB Malang',
                'faculty' => 'Pusat Studi Biosains & Bioteknologi',
                'lab_name' => 'Pusat Studi Biosains & Bioteknologi UB',
                'category' => 'Bioteknologi',
                'capacity' => 30,
                'address_description' => 'Jl. Veteran, Ketawanggede, Lowokwaru, Malang',
                'latitude' => -7.95250000,
                'longitude' => 112.61440000,
                'base_price_per_session' => 320000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNEJ-001',
                'campus_name' => 'Kampus UNEJ Tegalboto',
                'faculty' => 'Fakultas Teknik',
                'lab_name' => 'Laboratorium Pengujian Material & Metalurgi UNEJ',
                'category' => 'Material & Kimia',
                'capacity' => 25,
                'address_description' => 'Jl. Kalimantan No.37, Tegalboto, Jember',
                'latitude' => -8.16310000,
                'longitude' => 113.71620000,
                'base_price_per_session' => 220000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UM-001',
                'campus_name' => 'Kampus Utama UM Malang',
                'faculty' => 'Fakultas MIPA',
                'lab_name' => 'Laboratorium Terpadu Universitas Negeri Malang',
                'category' => 'Material & Kimia',
                'capacity' => 30,
                'address_description' => 'Jl. Semarang No.5, Sumbersari, Malang',
                'latitude' => -7.96120000,
                'longitude' => 112.61800000,
                'base_price_per_session' => 250000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNESA-001',
                'campus_name' => 'Kampus UNESA Lidah Wetan',
                'faculty' => 'Fakultas MIPA',
                'lab_name' => 'Pusat Riset Rekayasa Molekuler Unesa',
                'category' => 'Nanoteknologi',
                'capacity' => 25,
                'address_description' => 'Jl. Lidah Wetan, Lakarsantri, Surabaya',
                'latitude' => -7.30050000,
                'longitude' => 112.67400000,
                'base_price_per_session' => 230000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UPNJATIM-001',
                'campus_name' => 'Kampus UPN Rungkut',
                'faculty' => 'Fakultas Teknik',
                'lab_name' => 'Laboratorium Terpadu UPN Veteran Jawa Timur',
                'category' => 'Pertanian & Pangan',
                'capacity' => 30,
                'address_description' => 'Jl. Raya Rungkut Madya, Gunung Anyar, Surabaya',
                'latitude' => -7.33280000,
                'longitude' => 112.78850000,
                'base_price_per_session' => 210000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UTM-001',
                'campus_name' => 'Kampus UTM Telang',
                'faculty' => 'Fakultas Pertanian',
                'lab_name' => 'Laboratorium Riset Terpadu Universitas Trunojoyo Madura',
                'category' => 'Pertanian & Pangan',
                'capacity' => 25,
                'address_description' => 'Jl. Raya Telang, Kamal, Bangkalan, Madura',
                'latitude' => -7.12650000,
                'longitude' => 112.72120000,
                'base_price_per_session' => 190000.00,
                'is_active' => true,
            ],

            // --- SUMATERA ---
            [
                'lab_id' => 'LAB-UNAND-001',
                'campus_name' => 'Kampus Unand Limau Manis',
                'faculty' => 'Laboratorium Sentral Unand',
                'lab_name' => 'Laboratorium Sentral Universitas Andalas',
                'category' => 'Material & Kimia',
                'capacity' => 40,
                'address_description' => 'Limau Manis, Pauh, Kota Padang, Sumatera Barat',
                'latitude' => -0.91420000,
                'longitude' => 100.46300000,
                'base_price_per_session' => 270000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-USU-001',
                'campus_name' => 'Kampus USU Padang Bulan',
                'faculty' => 'Laboratorium Terpadu USU',
                'lab_name' => 'Laboratorium Terpadu Universitas Sumatera Utara',
                'category' => 'Farmasi & Medis',
                'capacity' => 35,
                'address_description' => 'Jl. Dr. Mansyur No.9, Padang Bulan, Medan',
                'latitude' => 3.56580000,
                'longitude' => 98.65620000,
                'base_price_per_session' => 290000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNRI-001',
                'campus_name' => 'Kampus UNRI Bina Widya',
                'faculty' => 'Fakultas MIPA',
                'lab_name' => 'Pusat Riset Bioteknologi Universitas Riau',
                'category' => 'Bioteknologi',
                'capacity' => 25,
                'address_description' => 'Kampus Bina Widya Km 12,5, Simpang Baru, Pekanbaru',
                'latitude' => 0.47890000,
                'longitude' => 101.37800000,
                'base_price_per_session' => 260000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNSRI-001',
                'campus_name' => 'Kampus Unsri Indralaya',
                'faculty' => 'Laboratorium Terpadu Unsri',
                'lab_name' => 'Laboratorium Terpadu Universitas Sriwijaya',
                'category' => 'Energi Terbarukan',
                'capacity' => 40,
                'address_description' => 'Jl. Raya Palembang - Prabumulih Km.32, Indralaya, Ogan Ilir',
                'latitude' => -3.22150000,
                'longitude' => 104.64800000,
                'base_price_per_session' => 280000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNILA-001',
                'campus_name' => 'Kampus Unila Gedung Meneng',
                'faculty' => 'Laboratorium Sentral Unila',
                'lab_name' => 'Laboratorium Sentral Universitas Lampung',
                'category' => 'Pertanian & Pangan',
                'capacity' => 30,
                'address_description' => 'Jl. Prof. Dr. Sumantri Brojonegoro No.1, Bandar Lampung',
                'latitude' => -5.36880000,
                'longitude' => 105.24400000,
                'base_price_per_session' => 240000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-USK-001',
                'campus_name' => 'Kampus USK Darussalam',
                'faculty' => 'Laboratorium Terpadu USK',
                'lab_name' => 'Laboratorium Terpadu Universitas Syiah Kuala',
                'category' => 'Material & Kimia',
                'capacity' => 35,
                'address_description' => 'Jl. Teuku Nyak Arief, Darussalam, Banda Aceh',
                'latitude' => 5.57010000,
                'longitude' => 95.36950000,
                'base_price_per_session' => 270000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-ITERA-001',
                'campus_name' => 'Kampus ITERA Lampung',
                'faculty' => 'Laboratorium Terpadu ITERA',
                'lab_name' => 'Laboratorium Terpadu ITERA Lampung',
                'category' => 'Energi Terbarukan',
                'capacity' => 30,
                'address_description' => 'Jl. Terusan Ryacudu, Way Huwi, Jati Agung, Lampung Selatan',
                'latitude' => -5.35780000,
                'longitude' => 105.31510000,
                'base_price_per_session' => 250000.00,
                'is_active' => true,
            ],

            // --- SULAWESI, KALIMANTAN, BALI & NUSA TENGGARA ---
            [
                'lab_id' => 'LAB-UNHAS-001',
                'campus_name' => 'Kampus UNHAS Tamalanrea',
                'faculty' => 'Pusat Riset Sains Hayati',
                'lab_name' => 'Pusat Riset Sains Hayati UNHAS',
                'category' => 'Bioteknologi',
                'capacity' => 30,
                'address_description' => 'Jl. Perintis Kemerdekaan Km.10, Tamalanrea, Makassar',
                'latitude' => -5.13280000,
                'longitude' => 119.48800000,
                'base_price_per_session' => 310000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNUD-001',
                'campus_name' => 'Kampus Unud Bukit Jimbaran',
                'faculty' => 'Laboratorium Sentral Unud',
                'lab_name' => 'Laboratorium Sentral Universitas Udayana',
                'category' => 'Farmasi & Medis',
                'capacity' => 35,
                'address_description' => 'Kampus Bukit Jimbaran, Badung, Bali',
                'latitude' => -8.79810000,
                'longitude' => 115.16250000,
                'base_price_per_session' => 300000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNMUL-001',
                'campus_name' => 'Kampus Unmul Gunung Kelua',
                'faculty' => 'Laboratorium Terpadu Unmul',
                'lab_name' => 'Laboratorium Terpadu Universitas Mulawarman',
                'category' => 'Lingkungan & Lingkup Laut',
                'capacity' => 25,
                'address_description' => 'Jl. Kuaro, Gunung Kelua, Samarinda Ulu, Samarinda',
                'latitude' => -0.47020000,
                'longitude' => 117.15310000,
                'base_price_per_session' => 240000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-ITK-001',
                'campus_name' => 'Kampus ITK Balikpapan',
                'faculty' => 'Laboratorium Riset Terpadu ITK',
                'lab_name' => 'Laboratorium Riset Terpadu ITK Balikpapan',
                'category' => 'Material & Kimia',
                'capacity' => 25,
                'address_description' => 'Jl. Soekarno-Hatta Km.15, Karang Joang, Balikpapan',
                'latitude' => -1.15110000,
                'longitude' => 116.86220000,
                'base_price_per_session' => 260000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-ULM-001',
                'campus_name' => 'Kampus ULM Banjarbaru',
                'faculty' => 'Laboratorium Terpadu ULM',
                'lab_name' => 'Laboratorium Terpadu Universitas Lambung Mangkurat',
                'category' => 'Lingkungan & Lingkup Laut',
                'capacity' => 30,
                'address_description' => 'Jl. A. Yani Km.36, Banjarbaru, Kalimantan Selatan',
                'latitude' => -3.44280000,
                'longitude' => 114.84100000,
                'base_price_per_session' => 230000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNRAM-001',
                'campus_name' => 'Kampus Unram Mataram',
                'faculty' => 'Laboratorium Sentral Unram',
                'lab_name' => 'Laboratorium Sentral Universitas Mataram',
                'category' => 'Pertanian & Pangan',
                'capacity' => 30,
                'address_description' => 'Jl. Majapahit No.62, Gomong, Mataram, NTB',
                'latitude' => -8.58880000,
                'longitude' => 116.09610000,
                'base_price_per_session' => 220000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNSRAT-001',
                'campus_name' => 'Kampus Unsrat Bahu',
                'faculty' => 'Fakultas Perikanan dan Ilmu Kelautan',
                'lab_name' => 'Laboratorium Terpadu Universitas Sam Ratulangi',
                'category' => 'Lingkungan & Lingkup Laut',
                'capacity' => 25,
                'address_description' => 'Jl. Kampus Unsrat Bahu, Manado, Sulawesi Utara',
                'latitude' => 1.45520000,
                'longitude' => 124.82600000,
                'base_price_per_session' => 250000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNTAD-001',
                'campus_name' => 'Kampus Untad Tondo',
                'faculty' => 'Laboratorium Sentral Untad',
                'lab_name' => 'Laboratorium Sentral Universitas Tadulako',
                'category' => 'Material & Kimia',
                'capacity' => 20,
                'address_description' => 'Jl. Soekarno-Hatta Km.9, Tondo, Palu, Sulawesi Tengah',
                'latitude' => -0.83610000,
                'longitude' => 119.89210000,
                'base_price_per_session' => 210000.00,
                'is_active' => true,
            ],

            // --- PAPUA, MALUKU & INSTANSI LAIN ---
            [
                'lab_id' => 'LAB-UNCEN-001',
                'campus_name' => 'Kampus Uncen Waena',
                'faculty' => 'Fakultas MIPA',
                'lab_name' => 'Laboratorium Riset Terpadu Universitas Cenderawasih',
                'category' => 'Bioteknologi',
                'capacity' => 20,
                'address_description' => 'Jl. Kampwolker, Waena, Jayapura, Papua',
                'latitude' => -2.59210000,
                'longitude' => 140.66900000,
                'base_price_per_session' => 280000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNPATTI-001',
                'campus_name' => 'Kampus Unpatti Poka',
                'faculty' => 'Laboratorium Terpadu Unpatti',
                'lab_name' => 'Laboratorium Terpadu Universitas Pattimura',
                'category' => 'Lingkungan & Lingkup Laut',
                'capacity' => 25,
                'address_description' => 'Jl. Ir. M. Putuhena, Poka, Ambon, Maluku',
                'latitude' => -3.65400000,
                'longitude' => 128.19120000,
                'base_price_per_session' => 240000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNDANA-001',
                'campus_name' => 'Kampus Undana Penfui',
                'faculty' => 'Laboratorium Terpadu Undana',
                'lab_name' => 'Laboratorium Terpadu Universitas Nusa Cendana',
                'category' => 'Pertanian & Pangan',
                'capacity' => 20,
                'address_description' => 'Jl. Adisucipto, Penfui, Kupang, NTT',
                'latitude' => -10.17220000,
                'longitude' => 123.66100000,
                'base_price_per_session' => 200000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-BRIN-005',
                'campus_name' => 'Kawasan Riset BRIN Ancol',
                'faculty' => 'Pusat Riset Oseanografi BRIN',
                'lab_name' => 'Pusat Riset Oseanografi BRIN Ancol',
                'category' => 'Lingkungan & Lingkup Laut',
                'capacity' => 30,
                'address_description' => 'Jl. Pasir Putih I No.1, Ancol Timur, Jakarta Utara',
                'latitude' => -6.12150000,
                'longitude' => 106.84310000,
                'base_price_per_session' => 350000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNIMED-001',
                'campus_name' => 'Kampus Unimed Willem Iskandar',
                'faculty' => 'Fakultas MIPA',
                'lab_name' => 'Laboratorium Terpadu Universitas Negeri Medan',
                'category' => 'Material & Kimia',
                'capacity' => 25,
                'address_description' => 'Jl. Willem Iskandar Pasar V, Medan, Sumatera Utara',
                'latitude' => 3.60800000,
                'longitude' => 98.71880000,
                'base_price_per_session' => 220000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNIB-001',
                'campus_name' => 'Kampus Unib Kandang Limun',
                'faculty' => 'Fakultas Pertanian',
                'lab_name' => 'Laboratorium Terpadu Universitas Bengkulu',
                'category' => 'Pertanian & Pangan',
                'capacity' => 20,
                'address_description' => 'Jl. Wr. Supratman, Kandang Limun, Bengkulu',
                'latitude' => -3.75700000,
                'longitude' => 102.27100000,
                'base_price_per_session' => 200000.00,
                'is_active' => true,
            ],
            [
                'lab_id' => 'LAB-UNIPA-001',
                'campus_name' => 'Kampus Unipa Amban',
                'faculty' => 'Laboratorium Riset Unipa',
                'lab_name' => 'Laboratorium Riset Terpadu Universitas Papua',
                'category' => 'Lingkungan & Lingkup Laut',
                'capacity' => 20,
                'address_description' => 'Jl. Gunung Salju, Amban, Manokwari, Papua Barat',
                'latitude' => -0.83510000,
                'longitude' => 134.06820000,
                'base_price_per_session' => 230000.00,
                'is_active' => true,
            ]
        ];

        foreach ($labs as $lab) {
            Laboratory::create($lab);
        }
    }
}
